### ISSUE TITLE
Setup with  gradle template

### ISSUE THREAD

**Issue by melanger** [JavaCardSpot-dev/ledger-u2f-javacard#5]
Read https://github.com/crocs-muni/javacard-gradle-template-edu/blob/master/INTEGRATION.md (thanks to Dusan Klinec)
• We will start with Variant A (easiest)
1. Your repository is already forked under JavaCardSpot-dev with team access rights assigned
2. Clone this repo to your local repo on your machine (git or GitHub app)
3. Download ZIP with gradle template: https://github.com/crocs-muni/javacard-gradle-template-edu/archive/master.zip
4. Copy template from ZIP to your local repo and move original applet source code to applet/src/main/java directory
5. Try and fix compilation, cap conversion and test execution
• (We will later cherry-pick changes for pull request to orig repo)

**Comment by J08nY** [comment]
Closed via 799e5352db2990c0b7c43790001e3b2549ae0ded.
